### ISSUE TITLE
Automatic link iOS module failed

### ISSUE THREAD

**Issue by anhtuank7c** [ambistudio/vasern#3]
As a user, I want to link module automatically via `react-native link` but right now we got an issue related to point to the wrong folder in `node_modules`.

See the attached image.

<img width="1314" alt="screen shot 2018-10-17 at 1 30 32 pm" src="https://user-images.githubusercontent.com/3163410/47068210-e0a73200-d215-11e8-8b7b-9a1cbbe323f3.png">

**Comment by hieunc229** [comment]
Thanks a @anhtuank7c for reporting this issue, my recent commit (https://github.com/ambistudio/vasern/commit/498cf10451130d8c804ef72144fb1edad14724d7) updated the source link for `npm`.

A new version of Vasern (0.2.73) on npm has been pushed. Please install the lastest version to apply this change.
